### ISSUE TITLE
Unimplemented part of seq deserialization

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/xml#24]
@futile reported hitting [this `unimplemented!()`](https://github.com/serde-rs/xml/blob/5be35f1ae118a7049bc2af427b6d25ca5e495ace/src/de/mod.rs#L839) when deserializing the following XML:

``` xml
<object id="11" name="testEllipse" x="102" y="38" width="21" height="14">
  <ellipse/>
</object>
```

Without the `<ellipse/>` it deserializes successfully.

**Comment by oli-obk** [comment]
unfortunately I cannot reproduce with the trivial

``` rust
    #[derive(Eq, PartialEq, Debug, Serialize, Deserialize)]
    struct Object {
        id: u8,
        name: String,
        x: u8,
        y: u8,
        width: u8,
        height: u8,
        ellipse: (),
    }
```

@futile, what's the exact type you were deserializing to?

**Comment by futile** [comment]
@oli-obk I should mention that the `ellipse` field is optional, and sometimes missing, because it's used as a marker for the `object` itself. I tried two different things, one was `ellipse: Option<()>`, which didn't work, and `#[derive(Deserialize)] struct Ellipse; [...] ellipse: Option<Ellipse>`, which also didn't work.

Here is my full code for `Object`: https://github.com/futile/tiled_loader/blob/1b476b030bc10528f6caa18c502feed97c6a140e/src/objects.rs#L48

**Comment by oli-obk** [comment]
right... I wrongly assumed that an empty tag should be treated as a `None`, when it should be treated as a `Some(T)` where `T` is some empty value (`()`, `vec![]`, ...).

**Comment by futile** [comment]
@oli-obk awesome, thanks for the quick fix! :)

**Comment by futile** [comment]
Hey again. I've got a follow-up issue I think. This code works now (with 0.9):

``` rust
ellipse: Option<()>,
```

However, this code

``` rust
#[derive(Debug, Deserialize)]
struct Ellipse;

...
ellipse: Option<Ellipse>,
...
```

hits the following `unimplemented!`: https://github.com/serde-rs/xml/blob/master/src/de/mod.rs#L227

**Comment by oli-obk** [comment]
0.9.1 fixes the second issue
